import type { LevelDefinition } from '../types/game'

// Data-driven level configuration. Difficulty increases per stage.
export const LEVELS: LevelDefinition[] = [
  {
    id: 1,
    name: '初入兔圈',
    gridSize: { rows: 6, cols: 6 },
    cardKinds: 4,
    minMatch: 3,
    trapRate: 0.02,
    timeLimit: 120,
    targetScore: 400,
    shuffles: 3,
    hints: 3,
    comboBonus: 0.1,
  },
  {
    id: 2,
    name: '萌新试炼',
    gridSize: { rows: 7, cols: 6 },
    cardKinds: 5,
    minMatch: 3,
    trapRate: 0.04,
    timeLimit: 105,
    targetScore: 800,
    shuffles: 3,
    hints: 2,
    comboBonus: 0.12,
  },
  {
    id: 3,
    name: '夜袭胡萝卜',
    gridSize: { rows: 7, cols: 7 },
    cardKinds: 6,
    minMatch: 3,
    trapRate: 0.07,
    moveLimit: 45,
    targetScore: 1350,
    shuffles: 2,
    hints: 2,
    comboBonus: 0.15,
  },
  {
    id: 4,
    name: '迷雾洞穴',
    gridSize: { rows: 8, cols: 7 },
    cardKinds: 7,
    minMatch: 4,
    trapRate: 0.1,
    timeLimit: 95,
    targetScore: 1900,
    shuffles: 2,
    hints: 2,
    comboBonus: 0.18,
  },
  {
    id: 5,
    name: '疾风试炼',
    gridSize: { rows: 8, cols: 8 },
    cardKinds: 8,
    minMatch: 4,
    trapRate: 0.12,
    moveLimit: 40,
    targetScore: 2600,
    shuffles: 1,
    hints: 2,
    comboBonus: 0.22,
  },
  {
    id: 6,
    name: '终章·月影',
    gridSize: { rows: 9, cols: 8 },
    cardKinds: 9,
    minMatch: 4,
    trapRate: 0.15,
    timeLimit: 90,
    moveLimit: 38,
    targetScore: 3500,
    shuffles: 1,
    hints: 1,
    comboBonus: 0.28,
  },
]

export default LEVELS
